name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Test suite
        run: php artisan test

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 165.227.96.233
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkVaEtadABZxiFEyCV/gO4uTzCkqh6W+D7QvtwbfvA66fOHndrJ5JZElOQp2fl6A9x50qZ9K2Nt1C0Hr92aMXgokAK2U5atVwAOZ/B3YYjWol8XlGSE06K67sgfvq1qAJLFUMsW6ZUjScsRrqcenEfFjJa6L8qWBFJ4Jy4nObvDiKbW5RueEXMTkxoxrHXabymsQctcETKYt4OXw36Hig3RqkM9uODJTbc66a1iSItDwWGyaQ5ic3PUb3gYb8aJzY2rNH5+RPtZHnzQlHStrrJMl//KraUOnXO5vsI0Y/rWn43/uIteV5Q2xmyarAkXDfRMfbEjXh/F6/vwHFkRm5tkAtiGVNYZL++0CMSwo2YQWBRSR1Pxe8dhHC6r7dbOrVQZ9wqXgv5Z4KNINv+/kUjHIN6yhful53LkMO157gi4SjFywDVLKfN/L1C10EM1Y+t3Box1yC2iGRjab0NvPy7OOjQfPLkAvl7LZQyZPcEC9Ni/rAHqi/OFTP6H8KRdxXMIvGKsm2SP/yuZwitsm4Z83hLxWRThcRDp9WsOWjeD8MQogguwaWKaOEf+NHpV6cCOgAGXW3YdM0vUqjXxRs5aGxmqdNuETB57ogNIuTiDc4TOSSrMiWEjJ4I3sdK7O0gIZmR8Nznu4DxZjMGEAf+CPdgPOBk4twGX6QBGHSPtQ== yowelikachala@gmail.com
          username: root

          script:
            cd /var/www/YowFitWeb
            git remote update
            git pull origin main
            composer install
            npm install
            php artisan migrate
