name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      laravel.test:
        image: sail-8.3/app
        ports:
          - 80:80
          - 5173:5173
        env:
          APP_PORT: 80
          VITE_PORT: 5173

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.ci .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Corrected from 'tests'
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/YowFitWeb
            git remote update
            git pull origin main
            composer install --optimize-autoloader
            npm install --production
            npm run build
            php artisan migrate
